#ifndef _PROCESS_FUNCTIONS_H_
#define _PROCESS_FUNCTIONS_H_

#include "w25qxx.h"
#include "rotaryEncoder.h"
#include "ILI9341.h"

#include "processActions.h"

/// Main menu panel

#define ENCODER_LOWER_LIMIT_MENU 1 // OP_CALCULATE_INDUCTANCE
#define ENCODER_UPPER_LIMIT_MENU 3 // OP_GENERATE_SIGNALS

#define FRAME_GRAPH_HT 120
#define FRAME_GRAPH_OFFSET 40
#define BACKGROUND_COLOR_MENU DEFAULT_BACKGROUND_COLOR
#define TEXT_COLOR_MENU 0xEF7D

#if (SCR_HT == 320)
#define DEFAULT_TOP_OFFSET_IMAGES 80
#else
#define DEFAULT_TOP_OFFSET_IMAGES 0
#endif

/// General settings panel

#define LETTER_SPACING_SIZE DEFAULT_LETTER_SPACING_SIZE
#define MAX_SIGNAL_SETTING_SIZE 11 // Longest string to store is "1000000 Hz"

#define INACTIVE_BLINK_DIGIT_TIME 230
#define ACTIVE_BLINK_DIGIT_TIME 850

#define FLASH_CONNECTION_ATTEMPTS 3

#define MENU_FRAME_BACKGROUND_COLOR 0x1085 // RGB: (16, 16, 41)
#define HEADER_PANEL_COLOR 0x3987 // RGB: (58, 49, 58)

// IMPLEMENTATION: Reading (4 * 128) pages and then print the bytes into the TFT.
// This process it'd be repeat at least 4 times to complete the 512 pages read (equal to 131072 Bytes)
// 512 pages is equal to ((16 * 256 * 8) Bytes [32 KB Block size] * 4 [Image's fragments]) / 256 Bytes [Bytes per page].
// NOTE: It takes 73 mS to process and print a (240 x 240) pixel image when SPI clock is setting to 36 MHz. When using an SD card, it takes 452 mS

#define BUFFER_IDX_FRAGMENT 6

#define TFT_LINES_HEIGHT_PER_QUARTER_IMAGE 60
#define QUARTER_IMAGE_BYTES_LENGTH (TFT_LINES_HEIGHT_PER_QUARTER_IMAGE * SCR_WD * BYTES_SIZE_TO_TYPE_16) // 28800 Bytes
#define TOTAL_SECTORS_TO_PROCESS_QUARTER_IMAGE 8 // (7.0312 + 1) \equalTo 8 x 4096 Bytes = 32768
#define TOTAL_FRAGMENTS_TO_PROCESS_ENTIRE_IMAGE (SCR_HT / (float)(((QUARTER_IMAGE_BYTES_LENGTH / BYTES_SIZE_TO_TYPE_16) / BUFFER_IDX_FRAGMENT) / SCR_HT))
#define TOTAL_FRAGMENTS_TO_PROCESS_ENTIRE_LAST_IMAGE (FRAME_GRAPH_HT / (float)(((QUARTER_IMAGE_BYTES_LENGTH / BYTES_SIZE_TO_TYPE_16) / BUFFER_IDX_FRAGMENT) / FRAME_GRAPH_HT))
#define MAX_PAGE_TO_PROCESS_ANY_IMAGE (32768 / 512 - 1)

#define TOTAL_SECTORS_TO_PROCESS_FRAGMENTS_IMAGE 8 // 8 [(16384 * 2) / 4096]
#define TOTAL_SECTORS_TO_PROCESS_ENTIRE_IMAGE (4 * TOTAL_SECTORS_TO_PROCESS_FRAGMENTS_IMAGE)

#define BATTERY_STATES_FRAGMENT_WIDTH 28
#define BATTERY_STATES_FRAGMENT_HEIGHT 15
#define BATTERY_STATES_FRAGMENT_BYTES_LENGTH (BATTERY_STATES_FRAGMENT_WIDTH * BATTERY_STATES_FRAGMENT_HEIGHT * 5 * BYTES_SIZE_TO_TYPE_16)
#define BATTERY_STATES_FRAGMENT_SECTOR_FRAGMENT 17
#define BATTERY_STATES_FRAGMENT_OFFSET -224

#define LOGO_IMAGE_WIDTH 186
#define LOGO_IMAGE_HEIGHT 33
// #define HEADER_IMAGE_BYTES_LENGTH (SCR_WD * LOGOTYPE_IMAGE_HEIGHT * BYTES_SIZE_TO_TYPE_16 + BATTERY_STATES_FRAGMENT_BYTES_LENGTH)
#define TOTAL_HEADER_IMAGE_HEIGHT (56 + HEIGHT_FLAME_EFFECT * 2)
#define TOTAL_HEADER_IMAGE_HEIGHT_POSITION 18
#define HEADER_IMAGE_SECTOR_FRAGMENT 13
#define HEADER_IMAGE_OFFSET 256

#define FRAME_PANEL_ELEMENTS_HEIGHT 1 

/// Generator signal settings panel

#define MULTIPLIER_EXPONENTIAL_NOTATION_REPRESENTATION

#define ENCODER_LOWER_LIMIT_SIGNAL_PANEL 0 // SIG_OP_CANCEL
#define ENCODER_UPPER_LIMIT_SIGNAL_PANEL 4 // SIG_OP_SET_FREQ

#ifndef MULTIPLIER_EXPONENTIAL_NOTATION_REPRESENTATION
#define ENCODER_LOWER_LIMIT_SIGNAL_MULTIPLIER_OPTIONS 0 // x1
#define ENCODER_UPPER_LIMIT_SIGNAL_MULTIPLIER_OPTIONS 4 // x10000
#else
#define ENCODER_LOWER_LIMIT_SIGNAL_MULTIPLIER_OPTIONS 0 // x10^0
#define ENCODER_UPPER_LIMIT_SIGNAL_MULTIPLIER_OPTIONS 5 // x10^5
#endif // !defined(MULTIPLIER_EXPONENTIAL_NOTATION_REPRESENTATION)

#define ENCODER_LOWER_LIMIT_SIGNAL_SIG_TYPE_OPTIONS 0 // SINE
#define ENCODER_UPPER_LIMIT_SIGNAL_SIG_TYPE_OPTIONS 2 // TRIANG

#define ENCODER_LOWER_LIMIT_SIGNAL_FREQUENCY 1 // 1 Hz
#define ENCODER_UPPER_LIMIT_SIGNAL_FREQUENCY 1000000 // 1 MHz

#ifndef MULTIPLIER_EXPONENTIAL_NOTATION_REPRESENTATION
#define DEFAULT_SIGNAL_MULTIPLIER 1000
#else
#define DEFAULT_SIGNAL_MULTIPLIER 3
#endif // !defined(MULTIPLIER_EXPONENTIAL_NOTATION_REPRESENTATION)
#define DEFAULT_SIGNAL_TYPE SIG_SINE
#define DEFAULT_SIGNAL_FREQUENCY 1000

#ifndef MULTIPLIER_EXPONENTIAL_NOTATION_REPRESENTATION
#define MARGIN_MIDDLE_CHARTS 1
#else
#define MARGIN_MIDDLE_CHARTS 4
#endif // !defined(MULTIPLIER_EXPONENTIAL_NOTATION_REPRESENTATION)
#define MARGIN_LEFT_CENTER_MIDDLE_CHARTS (SCR_WD / 2 + MARGIN_MIDDLE_CHARTS)
#define MARGIN_FILL_OUT_CHARTS 22
#define HEADER_PANEL_ELEMENTS_FRAME_HEIGHT 44
#define HEADER_PANEL_ELEMENTS_TOP_OFFSET (DEFAULT_TOP_OFFSET_IMAGES != 0 ? sizeof(gradientHBackgroundHeader_ST7789) / BYTES_SIZE_TO_TYPE_16 + FRAME_PANEL_ELEMENTS_HEIGHT + HEIGHT_FLAME_EFFECT + 10 : 8)
#define HORIZONTAL_PADDING_MIDDLE_CHARTS (6 * 2 + 1) /*MARGIN_MIDDLE_CHARTS-(MARGIN_MIDDLE_CHARTS/4)*/
#define HORIZONTAL_PADDING_FILL_OUT_CHARTS (6 * 2 + 15) /*MARGIN_FILL_OUT_CHARTS-(MARGIN_FILL_OUT_CHARTS/4)*/
#define VERTICAL_PADDING_CHARTS(row) (DEFAULT_TOP_OFFSET_IMAGES != 0 ? (DEFAULT_TOP_OFFSET_IMAGES - (HEADER_PANEL_ELEMENTS_FRAME_HEIGHT - 20) + 60 * (row % 4) + (row % 4) - 1 + 25 - (row > 1 ? -1 : 1) * 8 * (2 * (row % 2))) : (60 * (row % 4) + (row % 4) - 1 + 25 - 8 * (2 * (row % 2))))
#define VERTICAL_POSITION_TITLE_CHARTS(row) (DEFAULT_TOP_OFFSET_IMAGES != 0 ? (DEFAULT_TOP_OFFSET_IMAGES - (HEADER_PANEL_ELEMENTS_FRAME_HEIGHT - 20) + 60 * (row % 4) + (row % 4) - 1 - (row > 1 ? -1 : 1) * 8 * (2 * (row % 2))) : (60 * (row % 4) + (row % 4) - 1 - 8 * (2 * (row % 2))))

#define HEIGHT_CHARTS (60 - 2)
#define WIDTH_MIDDLE_CHARTS (SCR_WD / 2 - 2 * MARGIN_MIDDLE_CHARTS)
#define CONTENT_WIDTH_MIDDLE_CHARTS_SIZE (WIDTH_MIDDLE_CHARTS - 2 * HORIZONTAL_PADDING_MIDDLE_CHARTS)
#define WIDTH_FILL_OUT_CHARTS (SCR_WD - 2 * MARGIN_FILL_OUT_CHARTS)
#define CONTENT_WIDTH_FILL_OUT_CHARTS_SIZE (WIDTH_FILL_OUT_CHARTS - HORIZONTAL_PADDING_FILL_OUT_CHARTS / 2)

#define MAX_MULTIPLIER_DIGITS 5
#define MAX_FREQUENCY_DIGITS 10

#define BACKGROUND_CHARTS_COLOR 0x2124 // RGB: (33, 36, 33)
#define FRAME_CHARTS_COLOR(idle) (idle ? 0xB596 : 0x7BCF) // RGB: (181, 178, 181) | RGB: (123, 121, 123)
#define FRAME_HOVER_CHARTS_COLOR 0xEC71 // RGB: (239, 142, 140)
#define TITLE_CHARTS_COLOR(idle) (idle ? 0xE75E : 0xC67A) // RGB: (230, 235, 247) | RGB: (197, 206, 214)
#define TITLE_HOVER_CHARTS_COLOR 0xEDF7 // RGB: (238, 189, 189)
#define TEXT_CHARTS_COLOR(idle) (idle ? 0xEF5D : 0xB5B6) // RGB: (239, 235, 239) | RGB: (181, 182, 181) 
#define PANEL_ELEMENTS_COLOR(idle) (idle ? 0xBFBF : 0xF7DE) // RGB: (190, 245, 255) | RGB: (247, 251, 247)
#define PANEL_ELEMENTS_INACTIVE_COLOR 0xFFF6 // RGB: (255, 255, 181)
#define PANEL_ELEMENTS_ACTIVE_COLOR(idle) (idle ? 0xC7F8 : 0xFC71) // RGB: (198, 255, 198) | RGB: (255, 142, 140)
#define FRAME_PANEL_ELEMENTS_COLOR 0x2945 // RGB: (41, 41, 41)

typedef enum {
  INSTR_IMG = 0,
  INDUC_IMG = 1,
  QMETER_IMG = 2,
  SIG_IMG = 3,
  MBACK_IMG = 4,
  MFRAME_ENTIRE_IMG = 5,
  MFRAME_IMG = MAX_PAGE_TO_PROCESS_ANY_IMAGE,
  HEADER_IMG = MAX_PAGE_TO_PROCESS_ANY_IMAGE
} flashImages_t;

typedef enum {
  BATTERY_CHARGING = 0,
  BATTERY_FULL = 1,
  BATTERY_SEMI_FULL = 2,
  BATTERY_SEMI_EMPTY = 3,
  BATTERY_EMPTY = 4,
} batteryStates_t;

typedef enum {
  TYPE_NONE = 0,
  TYPE_UINT = 1,
  TYPE_INT = 2,
  TYPE_FLOAT = 3,
  TYPE_STRING = 4,
  TYPE_HIBRID = 5
} textTypes_t;

typedef enum {
  OP_NONE = 0,
  OP_CALCULATE_INDUCTANCE = 1,
  OP_CALCULATE_QUALITY_FACTOR = 2,
  OP_GENERATE_SIGNALS = 3
} operation_t;

typedef enum {
  SIG_OP_CANCEL = 0,
  SIG_OP_COMPLETE = 1,
  SIG_OP_SET_TYPE = 2,
  SIG_OP_SET_MULT = 3,
  SIG_OP_SET_FREQ = 4
} sig_operation_t;

extern bool flashPlugged;
extern batteryStates_t batteryStatus;

void printFromFlash(flashImages_t numImage, uint16_t topOffset = DEFAULT_TOP_OFFSET_IMAGES);
void displayMenu(operation_t &operation);
void processOperation(operation_t &operation);

void settingSignal(void);

#endif // _PROCESS_FUNCTIONS_H_
